# Generated by Django 6.0 on 2025-12-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='studentAge',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='message',
        ),
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(default='none@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
