# Generated by Django 6.0 on 2025-12-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_student_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentAge',
            new_name='age',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
